Add footer and page Sobre nosotros
root-code-software/junior-landing pull request #13
Opened 2023-01-16 20:52 UTC by Jesus-Gonzalez-Arroyo

fixes #8 

Agregando el footer y parte de nosotros al poryecto

2023-01-16 21:57 UTC, elias-miguel-vergara commented
espero aprobacion de @Israel-Laguan

2023-01-16 22:00 UTC, Israel-Laguan requested changes
Revert the glob changes

2023-01-16 22:00 UTC, Israel-Laguan commented on tailwind.config.js
> +    "./pages/*/.{js,ts,jsx,tsx}",
Please revert this change

2023-01-16 22:00 UTC, Israel-Laguan commented on pages/Nosotros.jsx
> +function Nosotros() {
Change to an arrow function

2023-01-16 22:18 UTC, Israel-Laguan commented
Build failed, please check

2023-01-19 12:49 UTC, Israel-Laguan commented on styles/SobreNosotros.module.css
> +    @apply w-11/12 m-auto mb-12 max-w-5xl rounded-2xl bg-[#125C13] flex flex-wrap items-center sm:w-3/5 sm:flex-nowrap sm:bg-transparent sm:w-4/5;
Please add `#125C13` to color variables in tailwind

2023-01-19 12:50 UTC, Israel-Laguan commented on styles/SobreNosotros.module.css
> +    @apply w-full bg-[#125C13] m-auto text-center p-8 text-[#fff] leading-8 rounded-xl;
I think `#fff` is already available as just `white`

Reference: https://tailwindcss.com/docs/customizing-colors

2023-01-19 22:06 UTC, Israel-Laguan approved these changes

2023-01-19 22:08 UTC, Israel-Laguan commented
It's not building, please check

2023-01-19 22:08 UTC, elias-miguel-vergara approved these changes

2023-01-20 02:29 UTC, joselyepez approved these changes

2023-01-20 02:29 UTC, joselyepez commented on components/SobreNosotros.jsx
> +                <Image
add alt attribute

2023-01-20 02:29 UTC, joselyepez commented on pages/_app.js
> +import SobreNosotros from "../Components/SobreNosotros"
add ;

2023-01-20 02:29 UTC, joselyepez commented on pages/index.js
> +import SobreNosotros from "../Components/SobreNosotros"
add ;

2023-01-20 05:05 UTC, Israel-Laguan commented
![image](https://user-images.githubusercontent.com/36519478/213621194-39d141ff-1a56-47e0-b493-d15ebbbcb37b.png)

![image](https://user-images.githubusercontent.com/36519478/213621300-2280b2d8-87ce-4c1d-99c6-19718873981b.png)

For reference this is how it looks on my side

2023-01-20 15:09 UTC, Jesus-Gonzalez-Arroyo commented
In the responsive part, we have to wait for Jose Luis to fix a part of the index since it generates a conflict in the responsiveness of the other components

2023-01-28 18:45 UTC, Jesus-Gonzalez-Arroyo commented
Conflictos resueltos

2023-01-28 18:45 UTC, Israel-Laguan approved these changes

2023-01-28 18:45 UTC, Israel-Laguan commented on styles/SobreNosotros.module.css
> +    @apply text-2xl text-center text-[#fff] my-3 font-extrabold;
Use white for this color

2023-01-28 20:37 UTC, Israel-Laguan approved these changes

2023-01-31 19:20 UTC, merged