Responsive desing Navbar
root-code-software/junior-landing pull request #19
Opened 2023-01-31 22:50 UTC by joselyepez

![Resonsive1](https://user-images.githubusercontent.com/93457870/215901632-71f78e14-57a5-4c7f-a7ed-2db45eb34113.PNG)
![Responsive2](https://user-images.githubusercontent.com/93457870/215901685-f208708a-6abc-477b-b14b-7dd0f963b71b.PNG)

2023-01-31 22:53 UTC, Israel-Laguan requested changes

2023-01-31 22:53 UTC, Israel-Laguan commented on components/Navbar.jsx
> +import { AiOutlineClose, AiOutlineMenu } from "react-icons/ai";
I don't think using a library only for these icons is worth, please use a svg from other place instead

2023-01-31 22:53 UTC, Israel-Laguan commented on components/Navbar.jsx
> +  const [nav, setNav] = useState(false);
Maybe use a name like "isNavOpen" instead

2023-02-02 12:07 UTC, Israel-Laguan commented on components/Navbar.jsx
> +  const [nav, isNavOpen] = useState(false);
```suggestion
  const [isNavOpen, setNavOpen] = useState(false);
```

2023-02-02 12:08 UTC, Israel-Laguan commented on components/Navbar.jsx
> +  const [nav, isNavOpen] = useState(false);
Change the rest of file and we can merge

2023-02-02 15:27 UTC, Israel-Laguan approved these changes

2023-02-02 18:48 UTC, elias-miguel-vergara approved these changes

2023-02-02 18:49 UTC, merged